### ISSUE TITLE
 com.smartbear.soapui:soapui:jar:5.7.0 was not found 

### ISSUE THREAD

**Issue by abhishekmaheshwari86** [SabreOSS/nimbus#2]
we are getting dependencies issue while running "mvn clean install".

Error:  Failed to execute goal on project nimbus-soapui-framework: Could not resolve dependencies for project com.sabre.qa.nimbus:nimbus-soapui-framework:jar:1.0.0-SNAPSHOT: com.smartbear.soapui:soapui:jar:5.7.0 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced

**Comment by kiranchitivolu** [comment]
@abhishekmaheshwari86 , please take the latest update and try again, issue should be resolved. SmarBear doesn't push their artifacts to maven central because of which you are getting this error. Now I have updated pom.xml forcing maven to look into https://www.soapui.org/repository/maven2 for dependencies first before looking into maven central, this should resolve the issue
